<project name="from_program" version="1.1">
    <ProjectDirectory>
        C:\roach_testing\flashpro\from_program
    </ProjectDirectory>
    <View>
        SingleSTAPLView
    </View>
    <LogFile>
        C:\roach_testing\flashpro\from_program\from_program.log
    </LogFile>
    <SerializationOption>
        Skip
    </SerializationOption>
    <programmer status="enable" type="FlashPro3" revision="UndefRev" connection="usb2.0">
        <name>
            05700
        </name>
        <id>
            05700
        </id>
    </programmer>
    <configuration>
        <Hardware>
            <FlashPro>
                <TCK>
                    4000000
                </TCK>
                <Vpp/>
                <Vpn/>
                <Vddl/>
                <Vdd>
2500                </Vdd>
            </FlashPro>
            <FlashProLite>
                <TCK>
                    4000000
                </TCK>
                <Vpp/>
                <Vpn/>
            </FlashProLite>
            <FlashPro3>
                <TCK>
                    4000000
                </TCK>
                <Vpump/>
            </FlashPro3>
        </Hardware>
        <Algo type="PDB">
            <filename>
                C:\roach_testing\flashpro\from_program\from_config.pdb
            </filename>
            <local>
                projectData\from_config.pdb
            </local>
            <SelectedAction>
                PROGRAM_FROM
            </SelectedAction>
        </Algo>
    </configuration>
</project>
