#!/bin/sh

if [ "$1" = "-u" ] ; then
unit=$2
else
unit=$1
fi

if [ "$unit" = "" ] ; then unit=0 ; fi

echo "Setting unit to $unit"

bitload -u $unit c3_16io
c3_set_e3 -u $unit
# set clock 2 to e3 rate, clock 0 and 3 to e1 and clock 1 10MHz
set_ss_vco -u $unit 1 0
set_ss_vco -u $unit -F 10000000 1
set_ss_vco -u $unit 4 2
set_ss_vco -u $unit 1 3
#  generate prbs15 on all 4 e3 channels
pdb $unit c3_e3prbs.pdb
genprbs15 -u $unit -N -c 0 -n 4 -l 0
