#!/bin/csh -f
#
#pragma ident "@(#)e1chk	1.2 10/10/03 EDT"
#

set unit = 0

if ( $#argv == 2 ) then
    if ( "$argv[1]" == "-u" ) then
	set unit=$argv[2]
    endif
endif

echo Testing unit $unit


bitload -u $unit combo16io
# set clock 2 to e3 rate, clock 0 and 3 to e1 and clock 1 10MHz
set_ss_vco -u $unit 1 0
set_ss_vco -u $unit -F 10000000 1
set_ss_vco -u $unit 4 2
set_ss_vco -u $unit 1 3
#  check prbs15 on all 16 e1 channels
pdb $unit e1chk.pdb
chkprbs15 -u $unit -N -c 0 -n 16 -l 0
