/* #pragma ident "@(#)PcdRequest.h	1.1 12/24/01 EDT" */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class PcdRequest */

#ifndef _Included_PcdRequest
#define _Included_PcdRequest
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: LOCK */
#undef PcdRequest_assert
#define PcdRequest_assert 0L
/* Inaccessible static: isInc */
/* Inaccessible static: incRate */
#undef PcdRequest_TOP_ALIGNMENT
#define PcdRequest_TOP_ALIGNMENT 0.0f
#undef PcdRequest_CENTER_ALIGNMENT
#define PcdRequest_CENTER_ALIGNMENT 0.5f
#undef PcdRequest_BOTTOM_ALIGNMENT
#define PcdRequest_BOTTOM_ALIGNMENT 1.0f
#undef PcdRequest_LEFT_ALIGNMENT
#define PcdRequest_LEFT_ALIGNMENT 0.0f
#undef PcdRequest_RIGHT_ALIGNMENT
#define PcdRequest_RIGHT_ALIGNMENT 1.0f
#undef PcdRequest_serialVersionUID
#define PcdRequest_serialVersionUID -7644114512714619750LL
#undef PcdRequest_serialVersionUID
#define PcdRequest_serialVersionUID 4613797578919906343LL
/* Inaccessible static: nameCounter */
#undef PcdRequest_serialVersionUID
#define PcdRequest_serialVersionUID -2728009084054400034LL
#undef PcdRequest_serialVersionUID
#define PcdRequest_serialVersionUID -5836846270535785031LL
/* Inaccessible static: dim */
/* Inaccessible static: spacer */
/* Inaccessible static: buttonCount */
/* Inaccessible static: cbg */
/* Inaccessible static: curPciName */
/* Inaccessible static: f */
/*
 * Class:     PcdRequest
 * Method:    PcdGetBoardInfoStrings
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_PcdRequest_PcdGetBoardInfoStrings
  (JNIEnv *, jobject);

/*
 * Class:     PcdRequest
 * Method:    PcdGetConfigInfo
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_PcdRequest_PcdGetConfigInfo
  (JNIEnv *, jobject, jstring);

/*
 * Class:     PcdRequest
 * Method:    PcdGetIntfcStrings
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_PcdRequest_PcdGetIntfcStrings
  (JNIEnv *, jobject, jstring);

/*
 * Class:     PcdRequest
 * Method:    PcdSaveConfigScript
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_PcdRequest_PcdSaveConfigScript
  (JNIEnv *, jobject);

/*
 * Class:     PcdRequest
 * Method:    PcdSetInterfaceBitfile
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_PcdRequest_PcdSetInterfaceBitfile
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
