#!/bin/csh -f

set unit = 0
set chan = 0
set prog = $0


while ($#argv > 0)
    if ("$argv[1]" == "-u") then
	set unit = $argv[2]
	shift
    else if ("$argv[1]" == "-c") then
	set chan = $argv[2]
	shift
    else
    	echo "Usage:  $prog [-u unit] [-c chan] (chan is 0 or 1)"
	exit 1
    endif
    shift
end

echo "unit is $unit; chan is $chan"

initpcd -u $unit -f sse_diffchk.cfg
#  check prbs15 on all 16 differential channels
chkprbs15 -u $unit -c $chan -n 1 -l 0
